document.addEventListener("DOMContentLoaded", function() {
    const paginaHome = "index.html"; 
    const arquivosExcluidos = ["index.html", "404.html"];
    
    // Pega o nome do arquivo atual e trata caracteres especiais (como %20)
    const arquivoAtual = window.location.pathname.split("/").pop() || "index.html";

    // Se for a página Home ou excluída, não faz nada
    if (arquivosExcluidos.includes(arquivoAtual)) return;

    function criarBotoes(anteriorLink, proximoLink) {
        // Estilo CSS
        const estilo = document.createElement('style');
        estilo.innerHTML = `
            .nav-float { 
                position: fixed; 
                bottom: 20px; 
                right: 20px; 
                display: flex; 
                gap: 10px; 
                z-index: 9999; 
            }
            .btn-nav { 
                padding: 10px 15px; 
                background: #4f46e5; 
                color: white; 
                text-decoration: none; 
                border-radius: 50px; 
                font-family: sans-serif; 
                font-weight: bold; 
                box-shadow: 0 4px 6px rgba(0,0,0,0.2); 
                transition: 0.2s; 
                font-size: 14px; 
                display: flex;
                align-items: center;
            }
            .btn-nav:hover { background: #3730a3; transform: translateY(-2px); }
            .btn-home { background: #2c3e50; } /* Cor diferente para a Home */
            
            @media (max-width: 600px) { 
                .nav-float { 
                    left: 10px; 
                    right: 10px; 
                    bottom: 15px;
                    justify-content: center; /* Centraliza no mobile */
                } 
                .btn-nav { 
                    flex: 1; /* Distribui tamanho igual */
                    justify-content: center; 
                    font-size: 12px; /* Letra um pouco menor no mobile para caber 3 botões */
                    padding: 10px 5px;
                } 
            }
        `;
        document.head.appendChild(estilo);

        const container = document.createElement('div');
        container.className = 'nav-float';

        // 1. Botão ANTERIOR (só cria se tiver link anterior)
        if (anteriorLink) {
            const btnAnt = document.createElement('a');
            btnAnt.href = anteriorLink;
            btnAnt.className = 'btn-nav';
            btnAnt.innerHTML = '⬅️ Ant';
            btnAnt.title = "Simulado Anterior";
            container.appendChild(btnAnt);
        }

        // 2. Botão HOME (sempre no meio)
        const btnHome = document.createElement('a');
        btnHome.href = paginaHome;
        btnHome.className = 'btn-nav btn-home';
        btnHome.innerHTML = '🏠 Home';
        container.appendChild(btnHome);

        // 3. Botão PRÓXIMO (só cria se tiver link próximo)
        if (proximoLink) {
            const btnProx = document.createElement('a');
            btnProx.href = proximoLink;
            btnProx.className = 'btn-nav';
            btnProx.innerHTML = 'Prox ➡️';
            btnProx.title = "Próximo Simulado";
            container.appendChild(btnProx);
        }

        document.body.appendChild(container);
    }

    // Lógica para descobrir a ordem lendo o index.html
    fetch(paginaHome)
        .then(response => response.text())
        .then(html => {
            const parser = new DOMParser();
            const doc = parser.parseFromString(html, 'text/html');
            // Pega todos os links dentro dos cards
            const links = Array.from(doc.querySelectorAll('.card a')).map(a => a.getAttribute('href'));
            
            // Descobre posição atual
            const atualLimpo = decodeURIComponent(arquivoAtual);
            const indexAtual = links.findIndex(link => decodeURIComponent(link) === atualLimpo);

            let anteriorLink = null;
            let proximoLink = null;

            if (indexAtual !== -1) {
                // Se não for o primeiro (index > 0), tem anterior
                if (indexAtual > 0) {
                    anteriorLink = links[indexAtual - 1];
                }
                // Se não for o último, tem próximo
                if (indexAtual < links.length - 1) {
                    proximoLink = links[indexAtual + 1];
                }
            }

            criarBotoes(anteriorLink, proximoLink);
        })
        .catch(err => console.error("Erro na navegação:", err));
});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const btnProx = document.createElement('a');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btnProx.href = proximoLink;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btnProx.className = 'btn-nav';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        btnProx.innerHTML = 'Prox ➡️';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    btnProx.title = "Próximo Simulado";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                container.appendChild(btnProx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.body.appendChild(container);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Lógica para descobrir a ordem lendo o index.html
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fetch(paginaHome)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .then(response => response.text())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .then(html => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const parser = new DOMParser();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const doc = parser.parseFromString(html, 'text/html');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Pega todos os links dentro dos cards
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const links = Array.from(doc.querySelectorAll('.card a')).map(a => a.getAttribute('href'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Descobre posição atual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const atualLimpo = decodeURIComponent(arquivoAtual);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const indexAtual = links.findIndex(link => decodeURIComponent(link) === atualLimpo);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let anteriorLink = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let proximoLink = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (indexAtual !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Se não for o primeiro (index > 0), tem anterior
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (indexAtual > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    anteriorLink = links[indexAtual - 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Se não for o último, tem próximo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (indexAtual < links.length - 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        proximoLink = links[indexAtual + 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                criarBotoes(anteriorLink, proximoLink);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .catch(err => console.error("Erro na navegação:", err));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
})
